#!/usr/bin/ruby
# metrics-history
# Generates the metrics of the whole history of an application.
# Antônio Terceiro (terceiro@dcc.ufba.br)
# Luiz Romário Santana Rios (luizromario@gmail.com)
# 
# Usage: ./metrics-history directory
#
# WARNING NOTE: Do not run this script in a work folder, since it 
# will checkout every commit in history, which may destroy your
# ongoing work.
#
require 'rubygems'
require 'grit'
require 'yaml'
require 'benchmark'

FILTER = /\.(c|h|cpp|cxx|cc|hpp|java)$/

class Grit::Commit
  def merge?
    self.parents.size > 1
  end
  def parentless
    self.parents.size == 0
  end
  def wanted?
    files = `git show --pretty=format: --name-only #{id}`.split
    matches = (files.any? { |path| path =~ FILTER })
    !merge? && matches 
  end
  def previous_wanted
    if merge? || parentless
      nil
    else
      previous = self.parents.first
      if previous.wanted?
        previous
      else
        previous.previous_wanted
      end
    end
  end
  def wanted_list
    commit = self.wanted? ? self : self.previous_wanted
    if commit
      result = []
      while commit
        result << commit
        commit = commit.previous_wanted
      end
      result
    else
      []
    end
  end
end

class EgyptRunner
  def self.metrics(commit)
    system("git checkout #{commit} > /dev/null 2>> git.log")
    yaml_metrics = `egypt-metrics . 2>> egypt.log`
    if yaml_metrics == "" then
      false
    else
      YAML.load_stream(yaml_metrics).documents
    end
  end
  def self.metricsCSV(commit)
    metr = metrics(commit)
    if metr then
      csv_string = ""
      csv_string << commit.id; csv_string << ","
      pa = commit.previous_wanted
      if pa then
        csv_string << commit.previous_wanted.id
      end
      csv_string << ",\""
      csv_string << commit.author.name; csv_string << "\","
      csv_string << commit.author.email; csv_string << ","

      metr = metr[0]
      csv_string << metr["average_coupling"].to_s; csv_string << ","
      csv_string << metr["average_lcom4"].to_s; csv_string << ","
      csv_string << metr["number_of_functions"].to_s; csv_string << ","
      csv_string << metr["number_of_modules"].to_s; csv_string << ","
      csv_string << metr["number_of_public_functions"].to_s; csv_string << ",\""
      csv_string << `git show --pretty=format: --name-only #{commit.id}`.split.join(',')
      csv_string << "\",\""
      csv_string << commit.authored_date.rfc2822; csv_string << "\""
    end
  end
end

if !ARGV[0] then
  puts "Usage: #{$PROGRAM_NAME} directory"
  exit
end
begin
  tree = Grit::Repo.new(ARGV[0]).commits.first
rescue Grit::InvalidGitRepositoryError
  puts "Error: Not a git repository."
  exit
end
previous_directory = Dir.pwd
Dir.chdir(ARGV[0])
system("echo \"#{Time.now}\" >> git.log")
system("echo \"#{Time.now}\" >> egypt.log")
system("git checkout master > /dev/null 2>> git.log")

File.open('metrics.csv', 'w') do |file|
  file.puts "commit_id,nearest_chngend_ancestral_id,author,e-mail,average_coupiling,average_lcom4,number_of_functions,number_of_modules,number_of_public_functions,changed_files,date\n"
  wl = tree.wanted_list
  if wl.size == 0 then
    puts "No relevant commits to process"
  else
    print "Processing " 
    if wl.size == 1 then
      puts "one commit"
    else
      puts "#{wl.size} commits..."
    end
  end
  error_counter = 0
  wl.each do |commit|
    if mcsv = EgyptRunner.metricsCSV(commit) then
      file.puts mcsv
      print "."
    else
      print "E"
      error_counter +=1
    end
  end
  if error_counter == 0 then
    puts "\nDone\n"
  elsif error_counter == 1 then
    print "\nOne error"
  else
    print "\n#{error_counter} errors"
  end
  puts " ocurred. Check egypt.log and git.log for more details.\n"
  system("git checkout master > /dev/null 2>> git.log")
end


